#pragma checksum "Pages\OrdersWindow_Show.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "122EBE44C5572079E6233AD141D01BD1B5519F7580392AB80441DBAA656959BC"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartTouchCRM.Pages;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SmartTouchCRM.Pages {
    
    
    /// <summary>
    /// OrdersWindow_Show
    /// </summary>
    public partial class OrdersWindow_Show : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock OrderShowName_Label;
        
        #line default
        #line hidden
        
        
        #line 23 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock customerFirstname;
        
        #line default
        #line hidden
        
        
        #line 25 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock customerLastname;
        
        #line default
        #line hidden
        
        
        #line 27 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock customerTelephone;
        
        #line default
        #line hidden
        
        
        #line 29 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock customerMail;
        
        #line default
        #line hidden
        
        
        #line 41 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock orderDate;
        
        #line default
        #line hidden
        
        
        #line 43 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock orderValue;
        
        #line default
        #line hidden
        
        /// <summary>
        /// ProductOrder_Data Name Field
        /// </summary>
        
        #line 45 "Pages\OrdersWindow_Show.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        public System.Windows.Controls.DataGrid ProductOrder_Data;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SmartTouchCRM;component/pages/orderswindow_show.xaml", System.UriKind.Relative);
            
            #line 1 "Pages\OrdersWindow_Show.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.OrderShowName_Label = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.customerFirstname = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.customerLastname = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.customerTelephone = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.customerMail = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.orderDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.orderValue = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.ProductOrder_Data = ((System.Windows.Controls.DataGrid)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

