//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("smarttouchdatabse.mdf")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("smarttouchdatabse_log.ldf")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("smarttouchmodel.context.tt")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("smarttouchmodel.tt")]


